spring:
  datasource:
    url: jdbc:mysql://localhost:13306/bus_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: finalproject
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  devtools:
    restart:
      enabled: true